<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('agent_stats', function (Blueprint $table) {
            $table->id();
            $table->string('month')->comment('Month in YYYY-MM format');
            $table->unsignedInteger('folder_count')->default(0);
            $table->unsignedInteger('profit')->default(0);
            $table->unsignedInteger('leads')->default(0)->comment('Number of leads generated by the agent');
            $table->foreignId('agent_id')->constrained('agents')->onDelete('cascade');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('agent_stats');
    }
};
